### PR TITLE
useForm can pass a name to be used with Hint/HintGroup components

### PR DESCRIPTION
**Pull request by moalamri**
Issue #45 
This will not have any breaking changes.
As the current users can continue to use the package with the same method: `useForm({...})`
Or give a name for each form in the component to have its own context under the passed name: `useForm("bestform", {...})`
And they can compose Hint & HintGroup with the form attribute using the same name:

 ``` svelte
<script>
const form2 = useForm("bestform1", {...})
const form1 = useForm("bestform2", {...})
</script>

<input name="name" use:validators={[required]} />
<Hint form="bestform1" for="name" on="required">HINT</Hint>

<input name="name" use:validators={[required]} />
<Hint form="bestform2" for="name" on="required">HINT</Hint>

<input name="email" use: validators={[required]} />
<HintGroup form="bestform1" for="email">
   <Hint on="required">HINT</Hint>
</HintGroup>

<input name="email" use:validators={[required]} />
<HintGroup form="bestform2" for="email">
   <Hint on="required">HINT</Hint>
</HintGroup>
 ```

### CODE REVIEW

**Comment by noahsalvi** [comment]
Awesome work! 

Could you format it with "npm run format", since if i do it, your changes will be lost 😆

Also I just added some testing to the project using playwright. It would be cool if you could write a simple test for it but no worries if you don't i'll do it, just let me know. 👍

**Comment by moalamri** [comment]
Hi, sorry for being late.

Sure, I will run formatter.
Regarding playwright, I have never managed to get it run especially in CD/CI. I mostly use cypress even though I find playwright more promising. 
I will see what I can do :)

**Comment by moalamri** [comment]
Formatted 👍🏻 
By the way. In my use case I have completely removed HintGroup and only uses Hint component to display either a group of errors or `required` alone.
Also added a `message` property to the ValidationError so I can pass my custom message.

```ts
  import { getContext } from "svelte";
  import { Form } from "../libs/form";

  export { name as for };
  export let hasErrors = false;

  // on specific type of validation error `Eg: number`
  export let on: string = undefined;
  let name = "";

  /** Hide other messages when `required` is among errors */
  export let requireAlone = true;
  /** Show the hint even when the field is untouched */
  export let showWhenUntouched = false;

  let form: {
    subscribe: (callback: (form: Form) => any) => void;
  } = getContext("svelte-use-form_form");

  $: touched = $form[name]?.touched ?? {};
  $: errors = $form[name]?.errors ?? {};
  $: errorsList = Object.entries(errors)
    .filter((err) => !err["required"])
    .map(([key, value]) => {
      if(on) {
        requireAlone = false;
        return {
          key,
          message: value[on].message
        }
      } else {
        return {
          key,
          message: value.message
        }
      }
    });
  $: errorRequired = errors["required"];
  $: hasErrors = Object.keys(errors).length > 0 && (touched || showWhenUntouched) as Boolean;
```
```svelte
{#if hasErrors}
  <div class="relative">
    {#if requireAlone && errorRequired}
      <div class="text-red-4 dark:text-red-4 text-sm">
        {errorRequired.message}
      </div>
    {:else}
      {#each errorsList as error}
        <div class="text-red-4 dark:text-red-4 text-sm">
          {error.message}
        </div>
      {/each}
    {/if}
  </div>
{/if}
```

A validator for example:
```ts
export function oneof(items: object[]): (value: string | number) => null | ValidationErrors {
  return (value: string | number | any): null | ValidationErrors => {
    const validate = v8n().includes(value).test(items.map(item => JSON.stringify(item)));
    return validate ? null : { oneof: { message: `Value must be one of ${items.map(item => item[0]).join(', ')}` } };
  };
}
```

**Comment by noahsalvi** [comment]
That's definitely an interesting approach.

When I implemented the Hint components I also had the idea of making them more "smart" by allowing them to iterate and display all the errors themself. The problems that I faced with this approach are that we define the messages that get displayed in the javascript part of our application and not the template. I mean this isn't really a big issue but I prefer to keep them in the template. Furthermore what about cases where you want a more complex message with maybe icons, images or styled text. You could of course allow both approaches and just switch between them but yeah...

Regarding the "hasErrors and not wanting to pass the form to "Input components", yeah I definitiely see the problem here, it would be annoying to always pass the form as a reference to the inputs. But what about using contexts to retrieve the form in the input component. This would also allow you to simply access the `valid` field of the form control.
https://svelte.dev/repl/73f50e7a79ea4e7687859106ef8feb09?version=3.53.1
(Repl showing a possible implementation)

**Comment by noahsalvi** [comment]
Maybe svelte-use-form could offer utility functions to retrieve the controls themselves from context.
`const control = getControl(name);`

**Comment by moalamri** [comment]
> That's definitely an interesting approach.
> 
> When I implemented the Hint components I also had the idea of making them more "smart" by allowing them to iterate and display all the errors themself. The problems that I faced with this approach are that we define the messages that get displayed in the javascript part of our application and not the template. I mean this isn't really a big issue but I prefer to keep them in the template. Furthermore what about cases where you want a more complex message with maybe icons, images or styled text. You could of course allow both approaches and just switch between them but yeah...
> 
> Regarding the "hasErrors and not wanting to pass the form to "Input components", yeah I definitiely see the problem here, it would be annoying to always pass the form as a reference to the inputs. But what about using contexts to retrieve the form in the input component. This would also allow you to simply access the `valid` field of the form control. https://svelte.dev/repl/73f50e7a79ea4e7687859106ef8feb09?version=3.53.1 (Repl showing a possible implementation)

To be honest what I most liked about your package is that it "automagically" bind itself to all my custom input components. I literally didn't have to change anything to my form except that I did what the package's name itself says :D `use:form`. And I would vote for keep it that way. 
I see what your approach in the repel would solve in my case. But since the hint component is retrieving an instance of the form, I could only sneak a variable back to the input component and that's all I need :D
Since your package automagically bind itself to all the input I see that only the `ignore` feature is what was missing. And now it support it which make it even better. Keep it magical @noahsalvi 😄 
I'm sorry I drifted you away from the main thing about this commit, do you think my commit would also solve the multi-form problem?

**Comment by noahsalvi** [comment]
Hahah awesome, nice to hear that!

"Automagically" i gotta use that somewhere in the docs ✍️🥴🤣

And I would say this PR is fine as it is, i'll probably create an issue for the other thing i just wrote above.
I'll merge it later and write a test myself if that's okay with you?

**Comment by moalamri** [comment]
> Hahah awesome, nice to hear that!
> 
> "Automagically" i gotta use that somewhere in the docs ✍️🥴🤣
> 
> And I would say this PR is fine as it is, i'll probably create an issue for the other thing i just wrote above. I'll merge it later and write a test myself if that's okay with you?

Please do add it to the docs 😄 it really impressed me when it did.

It's totally fine. You can merge at any time since it would work to solve that issue.
Speaking of testing. I was like "let me give playwright another try" since you mentioned it. And it only took me a day to completely throw cypress away and adapt playwright. I think I might help you cover some tests. I see that you adopted some. do you want me to add some for this commit?

**Comment by moalamri** [comment]
> Maybe svelte-use-form could offer utility functions to retrieve the controls themselves from context. `const control = getControl(name);`

I'm sorry I didn't notice your reply. was it a suggestion for supporting multi-forms?

**Comment by noahsalvi** [comment]
I gotta be honest I don't really have a lot of experience with e2e testing so I can't really say what is better. I know that angular uses cypress but I never really spend a lot of time using it. Playwright ist just the default testing framework sveltekit ships with, that's why I chose it ^^
What made you switch?

And yeah if you have the time to do it, then please do. Would definitely appreciate it. 🙏

**Comment by noahsalvi** [comment]
> > Maybe svelte-use-form could offer utility functions to retrieve the controls themselves from context. `const control = getControl(name);`
> 
> I'm sorry I didn't notice your reply. was it a suggestion for supporting multi-forms?

This wouldn't be relevant for this issue/PR. It's a proposal on how we could retrieve the state of a form control in a nested component like in your example.

**Comment by noahsalvi** [comment]
> I gotta be honest I don't really have a lot of experience with e2e testing so I can't really say what is better. I know that angular uses cypress but I never really spend a lot of time using it. Playwright ist just the default testing framework sveltekit ships with, that's why I chose it ^^ What made you switch?
> 
> And yeah if you have the time to do it, then please do. Would definitely appreciate it. 🙏

btw right now i'm using the default playwright library for writing tests but there also exists an experimental extension where you test only components themself. The advantage would be, that you don't have to add the test case as a route in sveltekit but rather as a simple component that is only used by the test.
https://playwright.dev/docs/test-components

I had some issues, when I tried it last time but maybe you'll get it to work?

**Comment by moalamri** [comment]
> I gotta be honest I don't really have a lot of experience with e2e testing so I can't really say what is better. I know that angular uses cypress but I never really spend a lot of time using it. Playwright ist just the default testing framework sveltekit ships with, that's why I chose it ^^ What made you switch?
> 
> And yeah if you have the time to do it, then please do. Would definitely appreciate it. 🙏

Playwright was promising when it first became popular, but it had some bugs and incompatibilities with the cd/ci I was using at that time. But man, when I had a look this week. It astonished me 👍🏻 Thank you for bringing it up. What I did for cypress to be compatible, I found playwright doing it in its core. And it's extremely fast comparing to cypress. Tests are cut from ~ 15min / run to ~ 10min / run

Anyways I think my approach to multi-forms isn't correctly working. Let me dig a little bit to this :D

**Comment by moalamri** [comment]
Was it necessary to expose the `data-testid` attribute?

**Comment by moalamri** [comment]
> > I gotta be honest I don't really have a lot of experience with e2e testing so I can't really say what is better. I know that angular uses cypress but I never really spend a lot of time using it. Playwright ist just the default testing framework sveltekit ships with, that's why I chose it ^^ What made you switch?
> > And yeah if you have the time to do it, then please do. Would definitely appreciate it. 🙏
> 
> btw right now i'm using the default playwright library for writing tests but there also exists an experimental extension where you test only components themself. The advantage would be, that you don't have to add the test case as a route in sveltekit but rather as a simple component that is only used by the test. https://playwright.dev/docs/test-components
> 
> I had some issues, when I tried it last time but maybe you'll get it to work?

Awesome! I didn't try this. I think you would run into issues since it is experimental xD. and I can't comprehend the idea that I can actually interact with a form using components only. I should try this; I also use the same approach as yours for testing :) but since I don't use Sveltekit, it is enough for me to run my tests on `vite` dev server.

**Comment by noahsalvi** [comment]
> Was it necessary to expose the `data-testid` attribute [here](https://github.com/noahsalvi/svelte-use-form/pull/47/commits/ed9671c09fd68f96b7638a3996d63b9a9b5d2f95)?

Hey sorry for the wait! (Currently busy with exams 😅)

Well I see how it makes sense but at the same time, it doesn't feel write to add a property only for testing purposes. I could be wrong about that since I am not an expert on testing but what about the following. We could expose the id and class of the div inside the Hint, allowing users to directly modify the styling (tailwind, etc.) and at the same time we would we could also use it as an id for testing.  

Remark: Well an even simpler approach would be to use the text of the hint as the selector in the tests but I actually believe it would be a great opportunity to add `class` and `id` to Hints.

What do you think?

**Comment by moalamri** [comment]
Hey @noahsalvi 
It's totally ok :D, take your time.

I agree that it could help alot to provide the ability to style the Hint container and the Hint component.
It is against the recommendation to expose the whole $$props, so if you going to provide props for class and id they could be assignable variables `export let _class` or `export let classes` since exporting `class` is not allowed.

Regarding the test attribute we can leave it at the website code for testing and never mention it to the end-user. But keep in mind that if any component has $$props, svelte will automatically expect any prop to be passed. So we better avoid it even if for testing. Go for your suggestion about using `id` for testing 👍🏻 

I have completely changed the library to use the new experimental typescript decorators for validation. still faced few issues with hidden inputs since your library scan for DOM elements so I had to export the form store to manually bind fields/values

**Comment by noahsalvi** [comment]
Actually as far as i remember you can expose class and id by aliasing the export.
```
let _class = "";
let _id = "";
export { _class as class, _id as id };
```typescript

Something like that. (I also used it for the attribute `for`)

Regarding the typescript decorators 🤯🤯🤯, I completely forgot they exist. 
I'll definitely have to look into the API when i have some spare time. Thanks!

Out of curiosity is there anyway you could maybe share how you're using it? maybe the repo or a simple usage example?
Just so that I have some inspiration for when I come back to this in the future.

**Comment by noahsalvi** [comment]
Also I just noticed that the Hint component already has support for setting the class attribute.
image

I'll change this to the way I described above and also add the ability to use id.
That way you could merge the master into your branch and simply change data-testid to use id instead 👍

**Comment by moalamri** [comment]
> Also I just noticed that the Hint component already has support for setting the class attribute. image
> 
> I'll change this to the way I described above and also add the ability to use id. That way you could merge the master into your branch and simply change data-testid to use id instead 👍

The component has $$props it will confuse the user since they can pass any props, I think your suggestion is much better 
```ts
let _class = "";
let _id = "";
export { _class as class, _id as id };
```

**Comment by moalamri** [comment]
> Actually as far as i remember you can expose class and id by aliasing the export.
> 
> ```ts
> let _class = "";
> let _id = "";
> export { _class as class, _id as id };
> ```
> 
> Something like that. (I also used it for the attribute `for`)
> 
> Regarding the typescript decorators 🤯🤯🤯, I completely forgot they exist. I'll definitely have to look into the API when i have some spare time. Thanks!
> 
> Out of curiosity is there anyway you could maybe share how you're using it? maybe the repo or a simple usage example? Just so that I have some inspiration for when I come back to this in the future.

Sure I will share it when I release the active sprint 😓😓

**Comment by moalamri** [comment]
Sorry for late, I have applied the suggested changes

**Comment by noahsalvi** [comment]
Awesome stuff! 🎉

**Comment by noahsalvi** [comment]
I just noticed an issue with the typing. If you look at `src/routes/examples/dynamic-form/+page.svelte` typescript reports that `Argument of type '{ username: { initial: string; }; }' is not assignable to parameter of type 'string'.t`.

Any idea how we could patch this? My current suggestion would be to change the order of the parameters of `useForm` and make it so that you'll have to write `useForm({}, "custom-name")` if you want to only modify the name.

**Comment by noahsalvi** [comment]
I've just changed the function definition to my solution above. 
If you have a better solution please let me know 😆

**Comment by moalamri** [comment]
I’m sorry man, it’s been a while and I have already forgotten some of what we discussed xD
Yes your solution looks good as optional params should be last passed, because I thought typescript would figure the params by type xD
Also another suggestion is `useForm(“form-name”: {})` where the form name is the formProperties key, and can be passed without a key to use default key “svelte-use-form”

is that possible? I didn’t try it as I don’t have my editor around.

**Comment by noahsalvi** [comment]
Ahh okay, well thanks for trying it out. 

So in that case I'll leave this change permanently for the foreseeable future. 👍

**Comment by moalamri** [comment]
Hi @noahsalvi 
Sorry for being late, I have promised to share my implementation of your library.
Unfortunately, I have completely changed my approach to building forms for Svelte. Since I have over 24 forms to build, I found it difficult to manually build/edit forms, therefore I have implemented a completely dynamic forms builder. It took me weeks but I found it the ideal solution.
I hope you have a great time; it was awesome to participate a little :D

**Comment by noahsalvi** [comment]
No worries! 
I definitely agree that svelte-use-form can't cover all use cases nevertheless it's nice to hear that you found another approach that is working out for you. 

I also wish you a great time and thank you for helping out! 😁

**Pull request merged**
